/**
 * Bilingual site copy for safdieconsulting.com.
 * EN is the locked, signed-off copy (Notion "Website — Structure & Content", Sept 18).
 * ES is a professional translation of the same copy — same structure, same meaning.
 */

export const EN = {
  nav: [
    { id: 'problems', label: 'Problems We Solve' },
    { id: 'how', label: 'How We Work' },
    { id: 'cases', label: 'Case Studies' },
    { id: 'about', label: 'About' },
    { id: 'faq', label: 'FAQ' },
    { id: 'contact', label: 'Contact' },
  ],
  navCtaLabel: 'Book a call',
  hero: {
    eyebrow: 'HR Tech advisory',
    headline: "When your product architecture can't hold the next stage of growth.",
    sub: 'HR Tech advisory for companies expanding into new countries or scaling up to enterprise-grade volume, backed by 25+ years building payroll, HCM, and EOR platforms across dozens of countries.',
    bullets: [
      'Product, platform and data architecture diagnosis',
      'Process and team assessment',
      'AI enablement',
    ],
    closer: "We diagnose what's breaking. We help your teams build the fix.",
    ctaPrimary: 'Book a call',
    ctaSecondary: 'See how we work',
  },
  numbers: [
    { value: '43', unit: '', label: 'Countries in a true Global Payroll Engine' },
    { value: '100', unit: '+', label: 'Countries: EOR platform build' },
    { value: '$200', unit: 'M', label: 'Series B supported' },
    { value: '40', unit: '%', label: 'Engineering cost reduction through AI-driven transformation' },
  ],
  labels: {
    problems: { num: '01', title: 'Problems We Solve', note: '' },
    how: { num: '02', title: 'How We Work', note: '' },
    engagement: { num: '03', title: 'How an engagement runs', note: 'Five steps, start to delivery.' },
    cases: { num: '04', title: 'Case Studies', note: '' },
    about: { num: '05', title: 'About', note: '' },
    faq: { num: '06', title: 'FAQ', note: '' },
    contact: { num: '07', title: 'Contact', note: '' },
  },
  paths: [
    {
      id: 'geographic',
      title: 'Geographic Expansion',
      strap: 'For teams taking their product into new countries.',
      intro: "A product's data architecture built for one market rarely survives the jump into three, ten, or fifty more. Currency, labor law, and language assumptions baked into a single-country build have to be re-architected, not patched.",
      tiles: [
        { id: 'global-scalability', title: 'Global scalability', hook: "Data models built for one market don't hold when you expand into new countries.", body: 'When companies expand into multiple countries, a single-country architecture has to be re-thought, not patched, to support multi-language and multi-jurisdiction requirements without duplicating the entire system per country.' },
      ],
    },
    {
      id: 'enterprise',
      title: 'Enterprise Scale-Up',
      strap: 'For teams taking their product from a small deployment to enterprise-grade volume.',
      intro: 'Performance, integrations, and data reconciliation that work for a few thousand records often fail under millions, and that failure shows up in production, not in testing.',
      tiles: [
        { id: 'integrations', title: 'Enterprise integrations', hook: "Simple ingestion pipelines don't survive contact with enterprise-grade systems.", body: 'A local or early-stage product usually connects through a simplified file or a lightweight interface. Enterprise clients bring a much larger number of interconnected systems, and the integrations required to serve them are bigger, more complex, and higher-stakes. Most HR Tech teams need outside help sizing and architecting that jump correctly the first time.' },
        { id: 'reconciliation', title: 'Data reconciliation & normalization', hook: "HRIS and payroll systems that don't speak the same data language create risk at every pay cycle.", body: "When employee and pay data move between HRIS and payroll systems without proper reconciliation and normalization, the result is silent errors: mismatched fields, duplicate records, payroll discrepancies that surface only after they've already caused damage. Getting this right is a distinct architecture problem, separate from integration itself." },
        { id: 'performance', title: 'Performance at scale', hook: 'A system built for one population breaks under the weight of a global one.', body: 'Local deployments are rarely built with global data volume in mind. When a client rolls the same product out across every country they operate in, performance assumptions that worked for a few thousand records can fail under millions, and that failure often shows up in production, not in testing.' },
      ],
    },
    {
      id: 'delivery',
      title: 'Delivery problems on both paths',
      strap: 'Whichever direction you are growing in, these two show up.',
      intro: '',
      tiles: [
        { id: 'implementation', title: 'Implementation friction', hook: "The deal closes, the resources committed on paper don't show up in practice.", body: "A recurring pattern: the client has the pain, agrees on the solution, and commits resources during the sales process. When implementation starts, the gap between what was promised and what's actually available shows up fast. In payroll implementations specifically, it's common for a client to discover mid-project that they don't have the internal staff or capacity to meet the agreed timeline, which pushes the go-live date and strains the relationship on both sides." },
        { id: 'misalignment', title: 'Product-engineering-business misalignment', hook: 'When product speaks business and engineering speaks technical, requirements get lost in translation.', body: "Product often sits closer to the business language, while engineering operates in a more technical one. Without a shared frame of reference, requirements drift from what the business asked for to what actually gets built, and that gap tends to surface right before go-live, when it's most expensive to fix." },
      ],
    },
  ],
  tiersIntro: "Three ways to work together. Whether your growth is geographic or organizational, the fix follows the same three-tier approach, depending on how much of the problem you've already mapped and how much support your team needs to execute it.",
  tiers: [
    { code: 'tier 01', name: 'Product Assessment', strap: 'A second opinion on your product architecture, from someone who has built it before.', body: "You get a full review of your current product and architecture and a written set of recommendations. No process review, no implementation plan, just a clear diagnosis of what's holding your platform back from enterprise scale.", bestFor: 'Best for teams who need an outside, expert read before deciding how much further to go.', timeline: 'About a week' },
    { code: 'tier 02', name: 'Scaling Readiness', strap: 'The diagnosis, the plan, and the metrics your team needs to execute it.', body: 'Beyond the product and architecture review, this tier looks at how your team delivers, both implementation and internal product development, and turns the findings into an action plan with clear success metrics your team can run with.', bestFor: 'This is where 25+ years scaling payroll, HCM, and EOR platforms applies most directly: the problems named on this page are exactly what this tier is built to diagnose and fix.', timeline: '10 days across 2-3 weeks' },
    { code: 'tier 03', name: 'Scaling Readiness + Oversight', strap: 'Everything in Scaling Readiness, plus a second set of expert eyes while your team builds.', body: "Adds a diagnosis of your team's structure and weekly oversight while your team executes the plan. You get flagged risks and progress reports every week, without handing over operational control — your team stays in the driver's seat, we supervise and report.", bestFor: 'Scoped to the plan, plus weekly check-ins for the duration. Best for higher-complexity engagements, or when you want expert accountability built into the execution phase, not just the diagnosis.', timeline: 'Scoped to the plan' },
  ],
  tiersCloser: 'Pricing depends on scope and complexity. Book a call to talk through what fits.',
  engagement: [
    { title: 'Discovery call', body: "We talk through the problem, your company's current situation, your objective, and a high-level read of where you are today versus where you want to get to." },
    { title: 'Proposal', body: 'We shape an engagement model to fit the problem: a deep diagnostic of your platform, a diagnostic plus a blueprint your team can execute, or a deeper diagnostic across processes, platforms, and products with milestones we track together. We adjust the proposal with you before an estimate goes out.' },
    { title: 'Scope agreement', body: 'If you decide to move forward, we sign the estimate and a short contract covering responsibilities, scope, and estimated timeline. The NDA is signed either right after the discovery call or at this stage, before work begins.' },
    { title: 'Working sessions', body: 'We work directly with your team: diagnostics, detailed plans, and a close look at your processes and platforms. What we need from you — documentation, system access, or a sandbox environment — depends entirely on the scope.' },
    { title: 'Delivery', body: 'What you receive depends on what was scoped: a document, a presentation, a detailed plan, a working prototype, or functioning code. Delivery always happens in a live session, sometimes more than one.' },
  ],
  fit: { yesLabel: 'Who this is for', yes: 'Funded, growth-stage HR Tech builders looking to expand globally or upmarket.' },
  caseLabels: { problem: 'The problem', approach: 'The approach', result: 'The result' },
  cases: [
    { id: 'case-1', title: 'Unifying payroll data across 14 countries', maps: 'Data reconciliation & normalization', problem: 'A global HR technology company needed to connect two HRIS platforms and fourteen country-specific payroll systems into a single source of truth for analysis. Each system used its own data format and field structure, with no shared standard across countries.', approach: 'Andrés led the architecture and build of a normalized data layer that reconciled all sixteen systems into one AI-driven analytics platform, resolving format inconsistencies at the integration layer instead of forcing every country system to conform to a single standard.', result: 'Two HRIS systems and fourteen payroll systems now feed one normalized platform, giving the organization a single, reliable view of data across every country it operates in. Reporting that once required manual reconciliation across sixteen systems now runs directly off the unified platform, cutting both the time and the cost of producing it.', figures: [{ value: '16', unit: '', label: 'Systems unified' }, { value: '14', unit: '', label: 'Country payroll platforms' }, { value: '1', unit: '', label: 'Source of truth' }] },
    { id: 'case-2', title: 'Closing a staffing gap without slipping the go-live', maps: 'Implementation friction', problem: "A payroll implementation client agreed to the solution and committed internal resources during the sales process. Once implementation started, the client discovered it didn't have the staff or capacity to execute its side of the plan on schedule.", approach: "Rather than waiting for the client to hire or reallocate people, Andrés designed and led a forward-deployed engineering model, using technology to absorb the work the client's team couldn't cover, instead of letting the timeline stall on a staffing problem.", result: 'The project shipped with a one-month delay instead of the extended slip a staffing gap like this typically causes.', figures: [{ value: '1', unit: 'mo', label: 'Actual delay' }, { value: '4', unit: 'mo', label: 'Baseline delay avoided' }, { value: '3', unit: 'mo', label: 'Revenue earlier' }] },
    { id: 'case-3', title: 'Clearing the path for Latin American expansion, market by market', maps: 'Global scalability', problem: 'A Latin American time management software company had built a solution for a country and wanted to expand into several others in the region. Before writing any code, the company needed to know which markets it could actually enter and what each one would legally require.', approach: "Andrés reviewed the labor and compliance requirements for each target country, including local calculation rules and shift rules, and identified local compliance partners the company would need in each market. In parallel, he guided the company's architects through a technical review of whether their configuration tables and codebase could support country-specific behavior without a rebuild. The review surfaced a requirement in one target market strict enough that it changed the company's plan for that country.", result: "The company decided to hold off on that market and moved forward with its other target countries, with a finalized plan for how the expansion would work in each one.", figures: [{ value: '1', unit: '', label: 'Market ruled out before build' }, { value: '0', unit: '', label: 'Lines of code wasted' }] },
  ],
  about: {
    headline: '25+ years building and scaling payroll, HCM, and EOR platforms across dozens of countries.',
    bio: 'As VP of Application Development at ADP GlobalView, he scaled the platform to 43 countries. As VP of Product Development at Atlas, he built the EOR platform to 100+ countries, supporting a $200M Series B. Most recently, as SVP of Engineering and Data Strategy, he led an AI-driven engineering transformation that cut engineering costs by 40% while building an agent-based Pay Intelligence platform.',
    facts: [['In HR Tech', '25+ years'], ['Built platforms at', 'ADP GlobalView · Atlas · Syndio · Others'], ['Domains', 'Payroll · HCM · EOR'], ['Reach', 'Dozens of countries']],
    linkedinLabel: 'Andrés on LinkedIn →',
  },
  faq: [
    { q: 'How long does an engagement typically take?', a: "It depends on the tier. A Product Assessment takes about a week. Scaling Readiness runs 10 days across 2-3 weeks, depending on your team's availability. Scaling Readiness + Oversight is scoped to the plan, plus weekly check-ins for the duration of execution." },
    { q: "What happens if our team can't execute the recommendation?", a: 'The diagnosis and plan are built for your team to execute, not for us to execute for you. If capacity turns out to be the real constraint, the Oversight tier adds weekly reporting and flagged risks while your team builds, without taking over the work. Where it helps, Andrés can also connect clients to his network of HR Tech and AI talent to close a specific gap.' },
    { q: 'Do you work with teams outside HR Tech?', a: "The core focus is HR Tech, but the expertise transfers to adjacent problems: data reconciliation, system integration, and architecture built to hold enterprise scale. Payments is one example of a space with the same underlying challenge. If your product has that kind of architecture problem, even outside HR Tech, it's worth a conversation." },
    { q: 'How does pricing work?', a: "Engagement pricing depends on scope, not a fixed rate card. A focused diagnostic on one system costs less than a full architecture review across multiple markets. We provide a specific range once we understand what you're trying to solve, during the initial call." },
    { q: 'Do you sign an NDA?', a: 'Yes. A standard NDA and confidentiality agreement are in place before any system access, code review, or team interview begins.' },
    { q: 'What do you need from our team?', a: "Access to the relevant systems, time from your architects or engineers for structured interviews, and, where the engagement involves market expansion, visibility into your actual expansion plans and timeline. We scope the specific access needed during the initial call, so your team isn't opening doors they don't need to." },
    { q: 'Do you work with our competitors?', a: "We don't take on simultaneous engagements with direct competitors. If a conflict comes up, we'll tell you before it becomes a problem." },
  ],
  contact: {
    headline: "Let's talk about what's holding your architecture back.",
    sub: 'Pick a time that works. No form before the call.',
    emailLabel: 'Email',
    linkedinCompanyLabel: 'LinkedIn — company',
    linkedinPersonalLabel: 'LinkedIn — Andrés',
    bookingLabel: 'Book 30 minutes',
    pendingLine1: 'Tidycal embed',
    pendingLine2: 'pending plan confirmation',
    privacyNote: 'Booking is handled by Tidycal, which collects your name and email under its own privacy policy. See our',
    privacyLinkText: 'privacy policy',
  },
  footer: { strap: 'HR Tech advisory for global product and data architecture.', siteColTitle: 'Site', legalColTitle: 'Legal', privacyLabel: 'Privacy Policy', cookieSettingsLabel: 'Cookie settings', note: '© 2026 Safdie Consulting. All rights reserved.' },
  cookieBanner: { text: 'We use Google Analytics to understand how this site is used. It loads only if you accept.', privacyLinkText: 'Privacy policy', accept: 'Accept', decline: 'Decline' },
  privacy: {
    title: 'Privacy Policy',
    updated: 'Last updated 2026-09-18',
    intro: 'Safdie Consulting ("we," "us," "our") operates safdieconsulting.com. This policy explains what personal data we collect, why, and how you can control it.',
    sections: [
      { title: 'What we collect', rows: [['Contact information.', 'If you email us, connect on LinkedIn, or book a call, we collect your name, email address, and anything else you choose to share.'], ['Booking data.', 'Scheduling a call through our booking widget (Tidycal) shares your name, email, and the details you provide with Tidycal, which processes that data under its own privacy policy.'], ['Analytics data.', 'We use Google Analytics to understand how visitors use this site, including pages viewed and general location. This runs only after you accept cookies through the banner on your first visit.']] },
      { title: 'Why we collect it', rows: [['', 'To respond to inquiries and schedule calls (legal basis: your consent, and steps necessary to enter a business relationship at your request).'], ['', 'To understand and improve the site (legal basis: your consent, given through the cookie banner).'], ['', 'We do not sell your data, and we do not use it for advertising.']] },
      { title: 'Who we share it with', rows: [['', 'Tidycal, for scheduling.'], ['', 'Google Analytics, for site analytics.'], ['', 'We do not share your data with any other third party except where required by law.']] },
      { title: 'How long we keep it', rows: [['', "We retain contact and booking data for the duration of our relationship with you and for a limited period afterward, then delete it unless we're required to keep it longer by law."]] },
      { title: 'Your rights', rows: [['', 'If you are in the EU or UK, you have the right to access, correct, delete, or export your personal data, and to withdraw consent at any time. To exercise any of these rights, contact us at info@safdieconsulting.com. If you are not satisfied with our response, you have the right to lodge a complaint with your local data protection authority.']] },
      { title: 'Cookies', rows: [['', 'We use a cookie consent banner on your first visit. Analytics cookies load only if you accept. You can change your preference at any time using the "Cookie settings" link in the footer.']] },
      { title: 'Changes to this policy', rows: [['', "If we make material changes, we'll update the date at the top of this page."]] },
    ],
  },
  notFound: { eyebrow: 'Error', title: 'Page not found', body: "The page you're looking for doesn't exist or was moved.", back: 'Back to home' },
  legalEyebrow: 'Legal',
  backLink: '← Back to home',
};

export const ES = {
  nav: [
    { id: 'problems', label: 'Problemas que resolvemos' },
    { id: 'how', label: 'Cómo trabajamos' },
    { id: 'cases', label: 'Casos de éxito' },
    { id: 'about', label: 'Sobre Andrés' },
    { id: 'faq', label: 'Preguntas frecuentes' },
    { id: 'contact', label: 'Contacto' },
  ],
  navCtaLabel: 'Reservar una llamada',
  hero: {
    eyebrow: 'Asesoría en HR Tech',
    headline: 'Cuando la arquitectura de tu producto no puede sostener la siguiente etapa de crecimiento.',
    sub: 'Asesoría en HR Tech para empresas que se expanden a nuevos países o escalan a volumen de nivel empresarial, respaldada por más de 25 años construyendo plataformas de nómina, HCM y EOR en decenas de países.',
    bullets: [
      'Diagnóstico de arquitectura de producto, plataforma y datos',
      'Evaluación de procesos y equipo',
      'Habilitación de IA',
    ],
    closer: 'Diagnosticamos qué está fallando. Ayudamos a tu equipo a construir la solución.',
    ctaPrimary: 'Reservar una llamada',
    ctaSecondary: 'Ver cómo trabajamos',
  },
  numbers: [
    { value: '43', unit: '', label: 'Países en un verdadero motor de nómina global' },
    { value: '100', unit: '+', label: 'Países: implementación de plataforma EOR' },
    { value: '$200', unit: 'M', label: 'Serie B respaldada' },
    { value: '40', unit: '%', label: 'Reducción de costos de ingeniería mediante transformación con IA' },
  ],
  labels: {
    problems: { num: '01', title: 'Problemas que resolvemos', note: '' },
    how: { num: '02', title: 'Cómo trabajamos', note: '' },
    engagement: { num: '03', title: 'Cómo funciona un proyecto', note: 'Cinco pasos, desde el inicio hasta la entrega.' },
    cases: { num: '04', title: 'Casos de éxito', note: '' },
    about: { num: '05', title: 'Sobre Andrés', note: '' },
    faq: { num: '06', title: 'Preguntas frecuentes', note: '' },
    contact: { num: '07', title: 'Contacto', note: '' },
  },
  paths: [
    {
      id: 'geographic',
      title: 'Expansión geográfica',
      strap: 'Para equipos que llevan su producto a nuevos países.',
      intro: 'La arquitectura de datos de un producto construida para un solo mercado rara vez sobrevive el salto a tres, diez o cincuenta más. Las suposiciones de moneda, legislación laboral e idioma integradas en una construcción de un solo país deben ser rediseñadas, no parcheadas.',
      tiles: [
        { id: 'global-scalability', title: 'Escalabilidad global', hook: 'Los modelos de datos construidos para un solo mercado no resisten cuando te expandes a nuevos países.', body: 'Cuando las empresas se expanden a varios países, una arquitectura de un solo país debe repensarse, no parchearse, para soportar requisitos multilingües y multijurisdiccionales sin duplicar todo el sistema por país.' },
      ],
    },
    {
      id: 'enterprise',
      title: 'Escalamiento empresarial',
      strap: 'Para equipos que llevan su producto de una implementación pequeña a un volumen de nivel empresarial.',
      intro: 'El rendimiento, las integraciones y la reconciliación de datos que funcionan con unos pocos miles de registros a menudo fallan con millones, y esa falla aparece en producción, no en pruebas.',
      tiles: [
        { id: 'integrations', title: 'Integraciones empresariales', hook: 'Los pipelines de ingesta simples no sobreviven el contacto con sistemas de nivel empresarial.', body: 'Un producto local o en etapa temprana suele conectarse mediante un archivo simplificado o una interfaz ligera. Los clientes empresariales traen una cantidad mucho mayor de sistemas interconectados, y las integraciones necesarias para atenderlos son más grandes, más complejas y de mayor riesgo. La mayoría de los equipos de HR Tech necesitan ayuda externa para dimensionar y diseñar ese salto correctamente la primera vez.' },
        { id: 'reconciliation', title: 'Reconciliación y normalización de datos', hook: 'Los sistemas de HRIS y nómina que no hablan el mismo lenguaje de datos crean riesgo en cada ciclo de pago.', body: 'Cuando los datos de empleados y de pago se mueven entre sistemas de HRIS y nómina sin una reconciliación y normalización adecuadas, el resultado son errores silenciosos: campos que no coinciden, registros duplicados, discrepancias de nómina que aparecen solo después de haber causado daño. Resolver esto bien es un problema de arquitectura distinto, separado de la integración en sí.' },
        { id: 'performance', title: 'Rendimiento a escala', hook: 'Un sistema construido para una población se rompe bajo el peso de una población global.', body: 'Las implementaciones locales rara vez se construyen pensando en volumen de datos global. Cuando un cliente despliega el mismo producto en cada país donde opera, las suposiciones de rendimiento que funcionaban con unos pocos miles de registros pueden fallar con millones, y esa falla suele aparecer en producción, no en pruebas.' },
      ],
    },
    {
      id: 'delivery',
      title: 'Problemas de implementación en ambos caminos',
      strap: 'Sea cual sea la dirección en la que creces, estos dos aparecen.',
      intro: '',
      tiles: [
        { id: 'implementation', title: 'Fricción de implementación', hook: 'El trato se cierra, los recursos comprometidos en el papel no aparecen en la práctica.', body: 'Un patrón recurrente: el cliente tiene el problema, acuerda la solución y compromete recursos durante el proceso de venta. Cuando comienza la implementación, la brecha entre lo prometido y lo realmente disponible aparece rápido. En implementaciones de nómina específicamente, es común que un cliente descubra a mitad de proyecto que no tiene el personal o la capacidad interna para cumplir el cronograma acordado, lo que retrasa la fecha de salida en vivo y tensiona la relación de ambos lados.' },
        { id: 'misalignment', title: 'Desalineación entre producto, ingeniería y negocio', hook: 'Cuando producto habla el lenguaje del negocio e ingeniería habla el lenguaje técnico, los requerimientos se pierden en la traducción.', body: 'Producto suele estar más cerca del lenguaje del negocio, mientras que ingeniería opera en uno más técnico. Sin un marco de referencia compartido, los requerimientos se alejan de lo que el negocio pidió respecto de lo que realmente se construye, y esa brecha suele aparecer justo antes de la salida en vivo, cuando es más costoso corregirla.' },
      ],
    },
  ],
  tiersIntro: 'Tres formas de trabajar juntos. Ya sea que tu crecimiento sea geográfico u organizacional, la solución sigue el mismo enfoque de tres niveles, según cuánto del problema ya hayas mapeado y cuánto apoyo necesite tu equipo para ejecutarlo.',
  tiers: [
    { code: 'nivel 01', name: 'Evaluación de producto', strap: 'Una segunda opinión sobre la arquitectura de tu producto, de alguien que ya la ha construido antes.', body: 'Obtienes una revisión completa de tu producto y arquitectura actuales y un conjunto de recomendaciones por escrito. Sin revisión de procesos, sin plan de implementación, solo un diagnóstico claro de qué está frenando tu plataforma para alcanzar escala empresarial.', bestFor: 'Ideal para equipos que necesitan una lectura experta y externa antes de decidir cuánto más avanzar.', timeline: 'Alrededor de una semana' },
    { code: 'nivel 02', name: 'Preparación para escalar', strap: 'El diagnóstico, el plan y las métricas que tu equipo necesita para ejecutarlo.', body: 'Más allá de la revisión de producto y arquitectura, este nivel analiza cómo entrega tu equipo, tanto en implementación como en desarrollo interno de producto, y convierte los hallazgos en un plan de acción con métricas de éxito claras que tu equipo puede ejecutar.', bestFor: 'Aquí es donde más de 25 años escalando plataformas de nómina, HCM y EOR aplican directamente: los problemas nombrados en esta página son exactamente lo que este nivel está diseñado para diagnosticar y resolver.', timeline: '10 días en 2-3 semanas' },
    { code: 'nivel 03', name: 'Preparación para escalar + Supervisión', strap: 'Todo lo de Preparación para escalar, más un segundo par de ojos expertos mientras tu equipo construye.', body: 'Añade un diagnóstico de la estructura de tu equipo y supervisión semanal mientras tu equipo ejecuta el plan. Recibes riesgos señalados e informes de progreso cada semana, sin ceder el control operativo — tu equipo permanece al mando, nosotros supervisamos e informamos.', bestFor: 'Ajustado al plan, más reuniones semanales durante toda la ejecución. Ideal para proyectos de mayor complejidad, o cuando quieres responsabilidad experta integrada en la fase de ejecución, no solo en el diagnóstico.', timeline: 'Ajustado al plan' },
  ],
  tiersCloser: 'El precio depende del alcance y la complejidad. Reserva una llamada para conversar qué se ajusta a tu caso.',
  engagement: [
    { title: 'Llamada de descubrimiento', body: 'Hablamos sobre el problema, la situación actual de tu empresa, tu objetivo y una lectura general de dónde estás hoy frente a dónde quieres llegar.' },
    { title: 'Propuesta', body: 'Diseñamos un modelo de proyecto según el problema: un diagnóstico profundo de tu plataforma, un diagnóstico más un plan que tu equipo pueda ejecutar, o un diagnóstico más profundo de procesos, plataformas y productos con hitos que seguimos juntos. Ajustamos la propuesta contigo antes de enviar una estimación.' },
    { title: 'Acuerdo de alcance', body: 'Si decides avanzar, firmamos la estimación y un contrato breve que cubre responsabilidades, alcance y cronograma estimado. El NDA se firma justo después de la llamada de descubrimiento o en esta etapa, antes de comenzar el trabajo.' },
    { title: 'Sesiones de trabajo', body: 'Trabajamos directamente con tu equipo: diagnósticos, planes detallados y una mirada cercana a tus procesos y plataformas. Lo que necesitamos de ti — documentación, acceso a sistemas o un entorno de prueba — depende por completo del alcance.' },
    { title: 'Entrega', body: 'Lo que recibes depende de lo acordado: un documento, una presentación, un plan detallado, un prototipo funcional o código en funcionamiento. La entrega siempre ocurre en una sesión en vivo, a veces más de una.' },
  ],
  fit: { yesLabel: 'Para quién es esto', yes: 'Empresas de HR Tech en etapa de crecimiento y con financiamiento, que buscan expandirse globalmente o escalar a nivel empresarial.' },
  caseLabels: { problem: 'El problema', approach: 'El enfoque', result: 'El resultado' },
  cases: [
    { id: 'case-1', title: 'Unificando datos de nómina en 14 países', maps: 'Reconciliación y normalización de datos', problem: 'Una empresa global de tecnología de RR. HH. necesitaba conectar dos plataformas de HRIS y catorce sistemas de nómina específicos de cada país en una única fuente de verdad para análisis. Cada sistema usaba su propio formato de datos y estructura de campos, sin un estándar compartido entre países.', approach: 'Andrés lideró la arquitectura y construcción de una capa de datos normalizada que reconcilió los dieciséis sistemas en una sola plataforma analítica impulsada por IA, resolviendo las inconsistencias de formato en la capa de integración en lugar de forzar a cada sistema de país a ajustarse a un estándar único.', result: 'Dos sistemas de HRIS y catorce sistemas de nómina ahora alimentan una plataforma normalizada, dándole a la organización una vista única y confiable de los datos en cada país donde opera. Los informes que antes requerían reconciliación manual entre dieciséis sistemas ahora se generan directamente desde la plataforma unificada, reduciendo tanto el tiempo como el costo de producirlos.', figures: [{ value: '16', unit: '', label: 'Sistemas unificados' }, { value: '14', unit: '', label: 'Plataformas de nómina por país' }, { value: '1', unit: '', label: 'Fuente de verdad' }] },
    { id: 'case-2', title: 'Cerrando una brecha de personal sin retrasar la salida en vivo', maps: 'Fricción de implementación', problem: 'Un cliente de implementación de nómina aceptó la solución y comprometió recursos internos durante el proceso de venta. Al iniciar la implementación, el cliente descubrió que no tenía el personal ni la capacidad para ejecutar su parte del plan según lo previsto.', approach: 'En lugar de esperar a que el cliente contratara o reasignara personal, Andrés diseñó y lideró un modelo de ingeniería desplegada hacia adelante, usando tecnología para absorber el trabajo que el equipo del cliente no podía cubrir, en vez de dejar que el cronograma se detuviera por un problema de personal.', result: 'El proyecto se entregó con un retraso de un mes en lugar del retraso mucho mayor que este tipo de brecha de personal suele causar.', figures: [{ value: '1', unit: 'mes', label: 'Retraso real' }, { value: '4', unit: 'meses', label: 'Retraso base evitado' }, { value: '3', unit: 'meses', label: 'Ingresos antes' }] },
    { id: 'case-3', title: 'Despejando el camino para la expansión en América Latina, país por país', maps: 'Escalabilidad global', problem: 'Una empresa latinoamericana de software de gestión de tiempo había construido una solución para un país y quería expandirse a varios otros de la región. Antes de escribir código, la empresa necesitaba saber a qué mercados podía realmente entrar y qué requeriría legalmente cada uno.', approach: 'Andrés revisó los requisitos laborales y de cumplimiento de cada país objetivo, incluidas las reglas locales de cálculo y de turnos, e identificó los socios de cumplimiento locales que la empresa necesitaría en cada mercado. En paralelo, guió a los arquitectos de la empresa en una revisión técnica de si sus tablas de configuración y su código podían soportar comportamiento específico por país sin una reconstrucción. La revisión reveló un requisito en un mercado objetivo lo suficientemente estricto como para cambiar el plan de la empresa para ese país.', result: 'La empresa decidió posponer ese mercado y avanzar con sus otros países objetivo, con un plan definitivo de cómo funcionaría la expansión en cada uno.', figures: [{ value: '1', unit: '', label: 'Mercado descartado antes de construir' }, { value: '0', unit: '', label: 'Líneas de código desperdiciadas' }] },
  ],
  about: {
    headline: 'Más de 25 años construyendo y escalando plataformas de nómina, HCM y EOR en decenas de países.',
    bio: 'Como VP de Desarrollo de Aplicaciones en ADP GlobalView, escaló la plataforma a 43 países. Como VP de Desarrollo de Producto en Atlas, construyó la plataforma EOR a más de 100 países, respaldando una Serie B de $200M. Más recientemente, como SVP de Ingeniería y Estrategia de Datos, lideró una transformación de ingeniería impulsada por IA que redujo los costos de ingeniería en un 40% mientras construía una plataforma de Inteligencia de Pagos basada en agentes.',
    facts: [['En HR Tech', 'Más de 25 años'], ['Plataformas construidas en', 'ADP GlobalView · Atlas · Syndio · Otras'], ['Dominios', 'Nómina · HCM · EOR'], ['Alcance', 'Decenas de países']],
    linkedinLabel: 'Andrés en LinkedIn →',
  },
  faq: [
    { q: '¿Cuánto dura típicamente un proyecto?', a: 'Depende del nivel. Una Evaluación de producto toma alrededor de una semana. Preparación para escalar toma 10 días en 2-3 semanas, según la disponibilidad de tu equipo. Preparación para escalar + Supervisión se ajusta al plan, más reuniones semanales durante toda la ejecución.' },
    { q: '¿Qué pasa si nuestro equipo no puede ejecutar la recomendación?', a: 'El diagnóstico y el plan están hechos para que tu equipo los ejecute, no para que nosotros los ejecutemos por ti. Si la capacidad resulta ser la restricción real, el nivel de Supervisión añade reportes semanales y riesgos señalados mientras tu equipo construye, sin tomar el control del trabajo. Cuando ayuda, Andrés también puede conectar a los clientes con su red de talento de HR Tech e IA para cerrar una brecha específica.' },
    { q: '¿Trabajan con equipos fuera de HR Tech?', a: 'El foco principal es HR Tech, pero la experiencia se transfiere a problemas afines: reconciliación de datos, integración de sistemas y arquitectura diseñada para soportar escala empresarial. Pagos es un ejemplo de un espacio con el mismo desafío subyacente. Si tu producto tiene ese tipo de problema de arquitectura, incluso fuera de HR Tech, vale la pena una conversación.' },
    { q: '¿Cómo funciona el precio?', a: 'El precio del proyecto depende del alcance, no de una tarifa fija. Un diagnóstico enfocado en un solo sistema cuesta menos que una revisión de arquitectura completa en varios mercados. Damos un rango específico una vez que entendemos qué estás tratando de resolver, durante la llamada inicial.' },
    { q: '¿Firman un NDA?', a: 'Sí. Un NDA estándar y un acuerdo de confidencialidad se firman antes de cualquier acceso a sistemas, revisión de código o entrevista con el equipo.' },
    { q: '¿Qué necesitan de nuestro equipo?', a: 'Acceso a los sistemas relevantes, tiempo de tus arquitectos o ingenieros para entrevistas estructuradas y, cuando el proyecto involucra expansión de mercado, visibilidad sobre tus planes y cronograma reales de expansión. Definimos el acceso específico necesario durante la llamada inicial, para que tu equipo no abra puertas que no necesita.' },
    { q: '¿Trabajan con nuestros competidores?', a: 'No aceptamos proyectos simultáneos con competidores directos. Si surge un conflicto, te lo diremos antes de que se convierta en un problema.' },
  ],
  contact: {
    headline: 'Hablemos sobre qué está frenando tu arquitectura.',
    sub: 'Elige un horario que te funcione. Sin formularios previos.',
    emailLabel: 'Correo',
    linkedinCompanyLabel: 'LinkedIn — empresa',
    linkedinPersonalLabel: 'LinkedIn — Andrés',
    bookingLabel: 'Reservar 30 minutos',
    pendingLine1: 'Integración de Tidycal',
    pendingLine2: 'pendiente de confirmación del plan',
    privacyNote: 'La reserva la gestiona Tidycal, que recopila tu nombre y correo bajo su propia política de privacidad. Consulta nuestra',
    privacyLinkText: 'política de privacidad',
  },
  footer: { strap: 'Asesoría en HR Tech para arquitectura global de producto y datos.', siteColTitle: 'Sitio', legalColTitle: 'Legal', privacyLabel: 'Política de privacidad', cookieSettingsLabel: 'Configuración de cookies', note: '© 2026 Safdie Consulting. Todos los derechos reservados.' },
  cookieBanner: { text: 'Usamos Google Analytics para entender cómo se usa este sitio. Solo se activa si aceptas.', privacyLinkText: 'Política de privacidad', accept: 'Aceptar', decline: 'Rechazar' },
  privacy: {
    title: 'Política de privacidad',
    updated: 'Última actualización: 2026-09-18',
    intro: 'Safdie Consulting ("nosotros") opera safdieconsulting.com. Esta política explica qué datos personales recopilamos, por qué, y cómo puedes controlarlos.',
    sections: [
      { title: 'Qué recopilamos', rows: [['Información de contacto.', 'Si nos escribes por correo, te conectas en LinkedIn o reservas una llamada, recopilamos tu nombre, correo electrónico y cualquier otro dato que decidas compartir.'], ['Datos de reserva.', 'Programar una llamada a través de nuestro widget de reserva (Tidycal) comparte tu nombre, correo y los detalles que proporciones con Tidycal, que procesa esos datos bajo su propia política de privacidad.'], ['Datos analíticos.', 'Usamos Google Analytics para entender cómo se usa el sitio, incluidas las páginas vistas y la ubicación general. Esto se activa solo después de aceptar las cookies en el banner de tu primera visita.']] },
      { title: 'Por qué lo recopilamos', rows: [['', 'Para responder consultas y programar llamadas (base legal: tu consentimiento, y los pasos necesarios para iniciar una relación comercial a tu solicitud).'], ['', 'Para entender y mejorar el sitio (base legal: tu consentimiento, otorgado a través del banner de cookies).'], ['', 'No vendemos tus datos, ni los usamos con fines publicitarios.']] },
      { title: 'Con quién lo compartimos', rows: [['', 'Tidycal, para la programación de llamadas.'], ['', 'Google Analytics, para analítica del sitio.'], ['', 'No compartimos tus datos con ningún otro tercero, salvo cuando lo exija la ley.']] },
      { title: 'Cuánto tiempo lo conservamos', rows: [['', 'Conservamos los datos de contacto y reserva durante la duración de nuestra relación contigo y por un período limitado después, y luego los eliminamos a menos que la ley nos exija conservarlos más tiempo.']] },
      { title: 'Tus derechos', rows: [['', 'Si estás en la UE o el Reino Unido, tienes derecho a acceder, corregir, eliminar o exportar tus datos personales, y a retirar tu consentimiento en cualquier momento. Para ejercer estos derechos, contáctanos en info@safdieconsulting.com. Si no estás satisfecho con nuestra respuesta, tienes derecho a presentar una queja ante tu autoridad local de protección de datos.']] },
      { title: 'Cookies', rows: [['', 'Usamos un banner de consentimiento de cookies en tu primera visita. Las cookies analíticas solo se activan si aceptas. Puedes cambiar tu preferencia en cualquier momento usando el enlace "Configuración de cookies" en el pie de página.']] },
      { title: 'Cambios a esta política', rows: [['', 'Si hacemos cambios materiales, actualizaremos la fecha en la parte superior de esta página.']] },
    ],
  },
  notFound: { eyebrow: 'Error', title: 'Página no encontrada', body: 'La página que buscas no existe o fue movida.', back: 'Volver al inicio' },
  legalEyebrow: 'Legal',
  backLink: '← Volver al inicio',
};
